spring:
  application:
    name: HesFintech

  profiles:
    active: dev
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

jwt:
  secret: qwerty232425ndjdysjrndhhsjjeesppsuurvxnhhfdkksdurnnsjj22234isknfnnfl8845jjdjdcscacassascbb353fdcd
  lifetime: 10m


am:
  openapi:
    dev-url: http://localhost:8080
springdoc:
  swagger-ui:
    path: /documentation
    try-it-out-enabled: true
  api-docs:
    path: /api-doc
  packages-to-scan: by.powerssolutions.hesfintech.controller